### ISSUE TITLE
Already paid and having trouble! Please help!

### ISSUE THREAD

**Issue by sandro-salles** [orkestral/superchats#15]
@orkestral pls help me.

I've paid for a licence, but i'm having trouble with the connection not staying up after qr scan and other issues.

Pls help me! No responses anymore from the guy who was chatting with me on whatsapp +55 61 8159-0153.

I'm on discord the username Sandro#5587

Pls, pls help!

**Comment by pasiga** [comment]
TypeError: _0x8337b6[_0x7e8585(...)] is not a function
