### ISSUE TITLE
Ayuda urgente No funciona la generación de QR

### ISSUE THREAD

**Issue by GhostWolf95** [orkestral/superchats#17]
Al querer genera el QR me lanza este error.
![superchats](https://user-images.githubusercontent.com/12677237/167215779-8b519c94-345f-484f-9a83-af6ee094ec6d.png)

agradezco me indiquen como resolverlo lo mas pronto posible

**Comment by Verzach3** [comment]
Hola, nunca he usado superchats pero si tengo experiencia con nodejs y con bots de whatsapp, una posible causa que puedo ver en la captura de pantalla es que si donde estas o en tu empresa tienen un firewall o un filtrado de dominios, este esta bloqueando las perticiones que nodejs esta haciendo hacia los servidores de licencia de superchats, lo unico que puedes hacer para solucionar el error es en el fltrado permitir el dominio license.superchats.io o a menos que tu bot no sea tan avanzado usar otra libreria que sea gratuita como baileys o whatsapp-web-js

**Comment by Verzach3** [comment]
Te digo lo de el firewall porque en el error se menciona fortinet que es un firewall, si llegas a necesitar mas ayuda puedes comunicarte conmigo por el correo que esta en mi perfil de github, por la cuenta de twitter Verzach31
