### ISSUE TITLE
Problem with multiple sessions

### ISSUE THREAD

**Issue by Guilherme-j10** [orkestral/superchats#19]
when creating more than one session and connecting to different devices in each of them, when calling the getHostDevice() method, for any of the sessions the host device data is the same in both.

![WhatsApp Image 2022-07-05 at 20 35 32](https://user-images.githubusercontent.com/55926786/177440261-3a719b8e-23fc-4002-a82a-6c95cda88e5e.jpeg)

**Comment by zakinshk** [comment]
@Guilherme-j10  você comprou esse superchats?
você sabia que essa biblioteca é gratuita, não ofuscada e se chama Baileys ?
https://github.com/adiwajshing/baileys/tree/master

Ele fez um fork do Baileys ofuscou o código e trocou o nome das funções!!!

**Comment by orkestral** [comment]
fix bug corretion in version 2.2.3
