### ISSUE TITLE
getmessageschat  preenchendo somente "from"

### ISSUE THREAD

**Issue by bigbdigital** [orkestral/superchats#2]
Ao executar a chamada getmessageschat  recebo o json somente com o "from" com o telefone do destinário, onde deveria ser o TO e o meu telefone deveria aparecer no from ou o from vir null.

abs

{
            "session": "1635721490588212",
            "type": "text",
            "id": "0AC95E14CC4A83E41AA519953BE3EC58",
            "from": "553186077856",
            "content": "Devo ter comido mosca",
            "isgroup": false,
            "participant": "",
            "timestamp": 1635726852
        },

**Comment by orkestral** [comment]
resolvido
