### ISSUE TITLE
.

### ISSUE THREAD

**Issue by edupoli** [orkestral/superchats#25]

**Comment by Bolsonabo2022** [comment]
Amei!!! Obrigado por economizar meu sofrido dinheiro.

**Comment by Bolsonabo2022** [comment]
https://open.spotify.com/track/5F2xRvRFkxDvqdFtUNAEyw Comemorar !!!

**Comment by Bolsonabo2022** [comment]
> 

🙏🙏🙏🙏🙏

**Comment by Bolsonabo2022** [comment]
Impecável. Projeto feito por desenvolvedores altamente qualificados na comunidade brasileira. é tão bom que quem usa typescript se fode com tudo quanto é any!!
