### ISSUE TITLE
Ja que o cara aqui adora copiar os outros , que tal provar do proprio veneno ? segue o codigo do superchats 

### ISSUE THREAD

**Issue by vingador77** [orkestral/superchats#26]
[Superchats-md v1.0.11.tgz](https://github.com/orkestral/superchats/files/9313020/Superchats-md.v1.0.11.tgz)

**Comment by Bolsonabo2022** [comment]
Silvanno salles, o cantor apaixonado.

**Comment by Bolsonabo2022** [comment]
não mudei de cidade nem de telefone só escolhi ser feliz.

**Comment by Bolsonabo2022** [comment]
https://open.spotify.com/track/6Jz48mgFAOayroClB7rE4L

**Comment by Bolsonabo2022** [comment]
### ESSA LIB É IMPECÁVEL !!!

**Comment by Bolsonabo2022** [comment]
Feita por brasileiros, a Superchats entra no mercado para falir dos mais pobres aos mais ricos, com sua capacidade extraórdinária de fazer "coisas" que as outras libs não fazem. O Projeto tem como base o Joe (O Programador, ele é o cara!!!) e nisso ele fez coisas que ninguém nesse mundo faça!! Ele é o primeiro do brasil a fazer uma lib em typescript a base de any e gambiarras! isso é extraordinário e é um avanço tecnológico na comunidade! Esse código refuta qualquer argumento feito por outras pessoas.

Melhores Programadores:
@NuevaGeneracionALB
@Joe
@Dark

**Comment by zakinshk** [comment]
Ele fez fork no Baileys e está vendendo??, que absurdo!!
projeto original
https://github.com/adiwajshing/baileys/tree/master

**Comment by orkestral** [comment]
Não tem fork nenhum
